module.exports = [
    {id:"1", title: "Curso de PHP", views: 500},
    {id:"2", title: "Curso de Laravel", views: 1100},
    {id:"3", title: "Curso de Angular", views: 3340},
    {id:"4", title: "Curso de GraphQl", views: 1100},
    {id:"5", title: "Curso de Vue", views: 2200},
    {id:"6", title: "Curso de React", views: 3300},
    {id:"7", title: "Curso de PHP", views: 500},
    {id:"8", title: "Curso de Laravel", views: 1100},
    {id:"9", title: "Curso de Angular", views: 3340},
    {id:"10", title: "Curso de GraphQl", views: 1100},
    {id:"11", title: "Curso de Vue", views: 2200},
    {id:"12", title: "Curso de React", views: 3300},
    {id:"13", title: "Curso de PHP", views: 500},
    {id:"14", title: "Curso de Laravel", views: 1100},
    {id:"15", title: "Curso de Angular", views: 3340},
    {id:"16", title: "Curso de GraphQl", views: 1100},
    {id:"17", title: "Curso de Vue", views: 2200},
    {id:"18", title: "Curso de React", views: 3300},
]